version: '2'
services:
  test:
    build: .
    command: 'make -f tests/Makefile'
    volumes:
      - ./bin/pg-copy-ch-dev:/bin/pg-copy-ch
      - ./tests:/tmp/tests
    working_dir: /tmp
    depends_on:
      - pg
      - ch
  pg:
    image: postgres:9.6
  ch:
    image: yandex/clickhouse-server
